name: Docker Image CI

permissions:
  contents: read
  packages: write

# Trigger only on push to main (after PR merge)
on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Log in to GitHub Container Registry
    - name: Log in to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Build Docker image
    - name: Build Docker image
      run: |
        REPO_OWNER_LOWER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
        docker build . -f Dockerfile -t ghcr.io/$REPO_OWNER_LOWER/nnbl-nextjs:${{ github.sha }}

    # Tag image as 'latest'
    - name: Tag Docker image as latest
      run: |
        REPO_OWNER_LOWER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
        docker tag ghcr.io/$REPO_OWNER_LOWER/nnbl-nextjs:${{ github.sha }} ghcr.io/$REPO_OWNER_LOWER/nnbl-nextjs:latest

    # Push both tags to GHCR
    - name: Push Docker image
      run: |
        REPO_OWNER_LOWER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
        docker push ghcr.io/$REPO_OWNER_LOWER/nnbl-nextjs:${{ github.sha }}
        docker push ghcr.io/$REPO_OWNER_LOWER/nnbl-nextjs:latest
